export interface IStylingProps {
  fontSize?: string
  fontWeight?: string
  textAlign?: string
  textTransform?: string
  justify?: string
  direction?: string
  align?: string
  flexWrap?: string
  gap?: string
  padding?: string
  margin?: string
  width?: string
  height?: string
  maxHeight?: string
  outline?: string
  color?: string
  bgColor?: string
  border?: string
  borderBottom?: string
  borderRadius?: string
  position?: string
  top?: string
  left?: string
  display?: string
  background?: string
  backgroundImage?: string
  overflow?: string
}
